### ISSUE TITLE
GNOME components not working

### ISSUE THREAD

**Issue by aiguofer** [regolith-linux/regolith-gnome-flashback#1]
Hi! first of all, just wanted to say thanks for this great DE. I've been using pure i3 for a while, but I do miss a lot of the functionality from a full fledged DE.

One thing I'm having trouble with is actually getting the DE functionality to work. I can see a bunch of the GSD components running in my session:

```
$ ps -ef | grep gsd
aiguofer 17145 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-a11y-settings
aiguofer 17147 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-sound
aiguofer 17148 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-media-keys
aiguofer 17151 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-print-notifications
aiguofer 17155 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-clipboard
aiguofer 17158 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-wacom
aiguofer 17160 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-mouse
aiguofer 17162 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-rfkill
aiguofer 17163 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-color
aiguofer 17165 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-xsettings
aiguofer 17169 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-power
aiguofer 17178 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-screensaver-proxy
aiguofer 17186 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-datetime
aiguofer 17215 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-sharing
aiguofer 17224 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-housekeeping
aiguofer 17227 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-smartcard
aiguofer 17232 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-keyboard
aiguofer 17361     1  0 14:23 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-printer
aiguofer 17380 16644  0 14:23 tty2     00:00:00 /usr/lib/gnome-disk-utility/gsd-disk-utility-notify
```

However, here's some things that aren't working:

- Media keys (volume, brightness, playback, etc)
- Power management (no auto-lock, auto suspend, etc)
- Display management (and `gnome-control-center display` gives me a segmentation fault)
- Notifications (`notify-send "TEST"` does nothing)

I also noticed that the `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1` isn't being launched either, so I still have to launch it from my i3 config.

Am I missing something to get these components to work?

Thanks!

**Comment by kgilmer** [comment]
Hi @aiguofer !  Um, yeah it sounds like something is not right with the gnome session.  I'm assuming you installed Regolith via the PPA on an existing system that already has i3?  Can you give me any details on your install?  Ubuntu 18.04 or 19.04?  

`/usr/bin/i3-gnome-flashback` is the script that launches i3 for Regolith.  Perhaps if you run `i3 -c /.config/i3-regolith` from a non X session you might get some error that provides a clue to the problem.  For reference, here is what my machine yields for the same command:

```
$ ps -ef | grep gsd
gdm       3743  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-xsettings
gdm       3747  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-a11y-settings
gdm       3750  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-clipboard
gdm       3754  2142  0 May26 tty1     00:08:55 /usr/lib/gnome-settings-daemon/gsd-color
gdm       3760  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-datetime
gdm       3763  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-housekeeping
gdm       3767  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-keyboard
gdm       3792  2142  0 May26 tty1     00:00:02 /usr/lib/gnome-settings-daemon/gsd-media-keys
gdm       3806  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-mouse
gdm       3824  2142  0 May26 tty1     00:00:06 /usr/lib/gnome-settings-daemon/gsd-power
gdm       3834  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-print-notifications
gdm       3840  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-rfkill
gdm       3861  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-screensaver-proxy
gdm       3863  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-sharing
gdm       3869  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-smartcard
gdm       3888  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-sound
gdm       3894  2142  0 May26 tty1     00:00:00 /usr/lib/gnome-settings-daemon/gsd-wacom
kgilmer  26352 26213  0 May26 tty2     00:00:01 /usr/lib/gnome-settings-daemon/gsd-print-notifications
kgilmer  26353 26213  0 May26 tty2     00:00:01 /usr/lib/gnome-settings-daemon/gsd-rfkill
kgilmer  26354 26213  0 May26 tty2     00:00:01 /usr/lib/gnome-settings-daemon/gsd-screensaver-proxy
kgilmer  26355 26213  0 May26 tty2     00:01:10 /usr/lib/gnome-settings-daemon/gsd-sharing
kgilmer  26359 26213  0 May26 tty2     00:00:01 /usr/lib/gnome-settings-daemon/gsd-smartcard
kgilmer  26364 26213  0 May26 tty2     00:00:01 /usr/lib/gnome-settings-daemon/gsd-sound
kgilmer  26370 26213  0 May26 tty2     00:00:03 /usr/lib/gnome-settings-daemon/gsd-wacom
kgilmer  26376 26213  0 May26 tty2     00:00:04 /usr/lib/gnome-settings-daemon/gsd-xsettings
kgilmer  26382 26213  0 May26 tty2     00:00:01 /usr/lib/gnome-settings-daemon/gsd-a11y-settings
kgilmer  26383 26213  0 May26 tty2     00:10:31 /usr/lib/gnome-settings-daemon/gsd-color
kgilmer  26387 26213  0 May26 tty2     00:00:03 /usr/lib/gnome-settings-daemon/gsd-clipboard
kgilmer  26389 26213  0 May26 tty2     00:00:51 /usr/lib/gnome-settings-daemon/gsd-housekeeping
kgilmer  26392 26213  0 May26 tty2     00:00:01 /usr/lib/gnome-settings-daemon/gsd-datetime
kgilmer  26398 26213  0 May26 tty2     00:00:06 /usr/lib/gnome-settings-daemon/gsd-media-keys
kgilmer  26400 26213  0 May26 tty2     00:00:03 /usr/lib/gnome-settings-daemon/gsd-keyboard
kgilmer  26403 26213  0 May26 tty2     00:00:14 /usr/lib/gnome-settings-daemon/gsd-power
kgilmer  26404 26213  0 May26 tty2     00:00:01 /usr/lib/gnome-settings-daemon/gsd-mouse
kgilmer  26446     1  0 May26 tty2     00:00:00 /usr/lib/gnome-settings-daemon/gsd-printer
kgilmer  26615 26213  0 May26 tty2     00:00:00 /usr/lib/gnome-disk-utility/gsd-disk-utility-notify
kgilmer  28806 28257  0 14:05 pts/2    00:00:00 grep --color=auto gsd
```

And, I don't even have `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1` as a file on my system.

**Comment by aiguofer** [comment]
Thanks for the quick response!

Indeed I installed it from the PPA on Ubuntu 19.04 with:

```
sudo add-apt-repository ppa:kgilmer/regolith-stable
sudo apt install regolith-desktop
```

I excluded all the GDM stuff in my output since I figured that didn't matter much.

Running `i3` from a non-X session just gives me `cannot open display`, even in verbose mode, which makes sense. I don't think the issue is with `i3` but with `gnome-flashback`, or in the way they interact together. What I find odd is that all of the `gnome-flashback` components seem to be running, but they just don't have any effect on my running session. Right now all the WM stuff works just fine, it's the extended functionality from a DE that doesn't.

As far as the `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1`, that's what launches a password prompt when you try to do some activity that requires higher privileges (like installing stuff from `ubuntu-software`). I have to run that manually with pure `i3`, not sure if that's something that `gnome-flashback` would handle (but since none of it seems to be working I can't really test).

**Comment by aiguofer** [comment]
Hmm, looking at the other Regolith components, maybe this issue lies with https://github.com/deuill/i3-gnome-flashback?

**Comment by kgilmer** [comment]
Well, Regolith's `regolith-gnome-flashback` was copied from https://github.com/deuill/i3-gnome-flashback.  It's hard for me know what to ask to further troubleshoot.  Perhaps you can install Regolith via the LiveCD into a VM and then do some comparisons that way?

**Comment by aiguofer** [comment]
Yeah makes sense, I looked into that repo without much help, but no worries we can close this if others aren't having the same issues. I just went back to using a standard i3 session without any gnome stuff (other than gnome-keyring) but using your `regolith-i3-wm` package since I don't want to build i3-gaps myself. I already have a bunch of scripts to handle DE anyway.

**Comment by kgilmer** [comment]
Understood, and thanks for following up.  By the way, I also started packaging a vanilla version of i3-gaps.  You may prefer that to using the Regolith variant since you are not using any of the styling: https://github.com/regolith-linux/speed-ricer
