### ISSUE TITLE
No way to disable notifications

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-gnome-flashback#4]
It seems that gnome-flashback is responsible for sending notifications and, if notifications are missed, displaying them in the tray (see https://wiki.gnome.org/Projects/GnomeFlashback#Notification_Daemon ).

This means that :

1. There's no way to disable notifications as the GNOME settings is linked to gnome-shell, not to gnome-flashback.
2. If a tray icon is added to i3xrocks, notifications will be displayed twice (once on the top right corner then, with the tray, in the bottom right where they sit until dismissed).

There should be a way to disable completely notifications in Regolith.

**Comment by kgilmer** [comment]
Does this suggestion from @balaketh in Slack not do what you want?
```
if you do gsettings set org.gnome.gnome-flashback notifications false
```

**Comment by ploum** [comment]
indeed, thanks a lot !
